name: Update HTML Page

on:
  repository_dispatch:
    types: [update_trigger]

jobs:
  update-web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Append Machine Info
      run: |
        # 接收傳過來的機器資訊並追加到本地 index.html 檔案最後面
        SRC_INFO="${{ github.event.client_payload.machine_info }}"
        touch index.html
        echo "${SRC_INFO}<br>" >> index.html

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actions@github.com"
        git add index.html
        git commit -m "Sync-Addr" || exit 0
        
        # 拉取雲端最新的 index.html 內容，Git 會自動把兩次的新增內容一行行接下去
        git pull --rebase origin main        
        git push origin main
